# Generated by Django 2.0 on 2017-12-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sclubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=200)),
                ('Event_Date', models.DateTimeField()),
                ('Organizer_Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sclubs.Club')),
            ],
        ),
    ]
