# Generated by Django 2.0 on 2017-12-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chairman', models.CharField(max_length=50)),
                ('Vice_Chairman', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('Club_email', models.CharField(max_length=100)),
                ('Club_Logo', models.CharField(max_length=1000)),
                ('Club_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_name', models.CharField(max_length=100)),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sclubs.Club')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sclubs.University'),
        ),
    ]
